fx_version "bodacious"
game "gta5"
lua54 "yes"

files {
	"metas/*"
}

data_file "WEAPONINFO_FILE" "metas/weapons.meta"
data_file "WEAPONINFO_FILE" "metas/weaponsnowball.meta"
data_file "WEAPONINFO_FILE" "metas/weapons_assaultrifle_mk2.meta"
data_file "WEAPONINFO_FILE" "metas/weaponcompactrifle.meta"
data_file "WEAPONINFO_FILE" "metas/weapongusenberg.meta"
data_file "WEAPONINFO_FILE" "metas/weaponheavypistol.meta"
data_file "WEAPONINFO_FILE" "metas/weaponmachinepistol.meta"
data_file "WEAPONINFO_FILE" "metas/weaponminismg.meta"
data_file "WEAPONINFO_FILE" "metas/weapons_pistol_mk2.meta"
data_file "WEAPONINFO_FILE" "metas/weaponrevolver.meta"
data_file "WEAPONINFO_FILE" "metas/weaponsnspistol.meta"
data_file "WEAPONINFO_FILE" "metas/weapons_snspistol_mk2.meta"
data_file "WEAPONINFO_FILE" "metas/weaponvintagepistol.meta"
data_file "WEAPONINFO_FILE" "metas/weaponbattleaxe.meta"
data_file "WEAPONINFO_FILE" "metas/weaponbottle.meta"
data_file "WEAPONINFO_FILE" "metas/weaponflashlight.meta"
data_file "WEAPONINFO_FILE" "metas/weaponhatchet.meta"
data_file "WEAPONINFO_FILE" "metas/weaponknuckle.meta"
data_file "WEAPONINFO_FILE" "metas/weaponmachete.meta"
data_file "WEAPONINFO_FILE" "metas/weaponpoolcue.meta"
data_file "WEAPONINFO_FILE" "metas/weaponstonehatchet.meta"
data_file "WEAPONINFO_FILE" "metas/weaponwrench.meta"
data_file "WEAPONINFO_FILE" "metas/weaponmusket.meta"
data_file "WEAPONINFO_FILE" "metas/weaponbullpuprifle.meta"
data_file "WEAPONINFO_FILE" "metas/weapons_bullpuprifle_mk2.meta"
data_file "WEAPONINFO_FILE" "metas/weapons_carbinerifle_mk2.meta"
data_file "WEAPONINFO_FILE" "metas/weapons_pumpshotgun_mk2.meta"
data_file "WEAPONINFO_FILE" "metas/weapons_smg_mk2.meta"
data_file "WEAPONINFO_FILE" "metas/weapons_specialcarbine_mk2.meta"
data_file "WEAPONINFO_FILE" "metas/weaponspecialcarbine.meta"
data_file "WEAPONINFO_FILE" "metas/weapon_tacticalrifle.meta"
data_file "WEAPONINFO_FILE" "metas/weapons_heavyrifle.meta"